code --install-extension aaron-bond.better-comments
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension karsany.vscode-ideal-theme
code --install-extension leizongmin.node-module-intellisense
code --install-extension luggage66.AWK
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-python.python
code --install-extension oderwat.indent-rainbow
code --install-extension OfHumanBondage.react-proptypes-intellisense
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension vsmobile.vscode-react-native